from fpdf import FPDF

class StrategicReportPDF(FPDF):
    report_font = "Helvetica"
    
    def set_font(self, family="", style="", size=0):
        if family == "Helvetica":
            family = self.report_font
        super().set_font(family, style, size)

    def header(self):
        # Header only on later pages
        if self.page_no() > 1:
            self.set_font("Helvetica", "I", 8)
            self.set_text_color(100, 116, 139) # slate-500
            self.cell(100, 8, "AgentBridge Global Career & Migration Blueprint", 0, 0, "L")
            self.cell(0, 8, f"Page {self.page_no()}", 0, 1, "R")
            self.set_draw_color(226, 232, 240) # slate-200
            self.line(15, 18, 195, 18)
            self.ln(4)
            
    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(148, 163, 184) # slate-400
        self.cell(100, 8, "Confidential - Generated by AgentBridge Multi-Agent AI", 0, 0, "L")
        self.cell(0, 8, f"Page {self.page_no()}", 0, 0, "R")

def calculate_budget_path(explorer, funding):
    best_path = None
    min_out_of_pocket = float('inf')
    
    for cost in funding.get('cost_analysis', []):
        code = cost.get('country_code')
        c_info = next((c for c in explorer.get('matched_countries', []) if c.get('country_code') == code), {})
        country_name = c_info.get('country_name', code)
        
        scholarships = [s for s in funding.get('matching_scholarships', []) if s.get('country_code') == code]
        top_scholarship = max(scholarships, key=lambda s: s.get('award_amount_usd', 0), default=None)
        scholarship_amt = top_scholarship.get('award_amount_usd', 0) if top_scholarship else 0
        scholarship_name = top_scholarship.get('name', 'No major scholarship matched') if top_scholarship else "No major scholarship matched"
        
        univ_type = "Public (Tuition Free / Low Fee)" if cost.get('annual_tuition_usd', 0) < 5000 else "Private / Institutional"
        
        hourly_wage = 12
        if code == "DE": hourly_wage = 15
        elif code == "JP": hourly_wage = 8
        elif code == "NL": hourly_wage = 16
        elif code == "AU": hourly_wage = 15
        elif code == "CA": hourly_wage = 12
        
        part_time_earnings = 960 * hourly_wage
        original_cost = cost.get('total_1yr_usd', 0)
        
        out_of_pocket = max(0, original_cost - scholarship_amt - part_time_earnings)
        affordability_score = max(1, min(10, round(10 - (out_of_pocket / 5000))))
        
        if out_of_pocket < min_out_of_pocket:
            min_out_of_pocket = out_of_pocket
            
            explanation = ""
            if code == "DE":
                explanation = "Germany offers tuition-free public university education, significantly lowering the upfront barrier. Combined with DAAD merit funding and student part-time work, the first-year out-of-pocket cost is fully offset, making it the most affordable strategic option."
            elif code == "JP":
                explanation = "Japan offers very low tuition fees at public universities and a reasonable cost of living. Sourcing local institutional waivers and part-time teaching/assistant roles provides a highly cost-effective gateway with excellent ROI."
            else:
                explanation = f"Relocating to {country_name} under this pathway utilizes high-value scholarship offsets combined with the maximum allowed part-time work hours, substantially reducing the initial cash-flow requirements while positioning you for premium local tech salaries."
                
            best_path = {
                'country_name': country_name,
                'country_code': code,
                'univ_type': univ_type,
                'scholarship_name': scholarship_name,
                'scholarship_amt': scholarship_amt,
                'part_time_earnings': part_time_earnings,
                'original_cost': original_cost,
                'out_of_pocket': out_of_pocket,
                'expected_salary': cost.get('expected_salary_usd', 0),
                'roi': cost.get('financial_roi_score', 0),
                'affordability_score': affordability_score,
                'explanation': explanation
            }
            
    return best_path

def generate_pdf_report(profile: dict, explorer: dict, funding: dict, simulation: dict = None, currency: str = "USD") -> bytes:
    pdf = StrategicReportPDF(orientation="P", unit="mm", format="A4")
    
    rate = 95.0 if currency == "INR" else 1.0
    symbol = "$"
    
    if currency == "INR":
        import os
        font_dir = "C:\\Windows\\Fonts"
        font_path = os.path.join(font_dir, "arial.ttf")
        if os.path.exists(font_path):
            try:
                pdf.add_font("ArialUnicode", fname=font_path)
                
                bd_path = os.path.join(font_dir, "arialbd.ttf")
                if os.path.exists(bd_path):
                    pdf.add_font("ArialUnicode", style="B", fname=bd_path)
                else:
                    pdf.add_font("ArialUnicode", style="B", fname=font_path)
                    
                it_path = os.path.join(font_dir, "ariali.ttf")
                if os.path.exists(it_path):
                    pdf.add_font("ArialUnicode", style="I", fname=it_path)
                else:
                    pdf.add_font("ArialUnicode", style="I", fname=font_path)
                    
                bi_path = os.path.join(font_dir, "arialbi.ttf")
                if os.path.exists(bi_path):
                    pdf.add_font("ArialUnicode", style="BI", fname=bi_path)
                else:
                    pdf.add_font("ArialUnicode", style="BI", fname=font_path)

                pdf.report_font = "ArialUnicode"
                symbol = "\u20b9"
            except Exception as e:
                print(f"Error registering Arial font: {e}")
                symbol = "Rs. "
        else:
            symbol = "Rs. "

    pdf.set_margins(15, 15, 15)
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    
    # Extract metrics for cover page and executive summary
    best_c_info = max(explorer.get('matched_countries', []), key=lambda c: c.get('match_score', 0), default={})
    best_country = best_c_info.get('country_name', 'Germany')
    best_country_code = best_c_info.get('country_code', 'DE')
    overall_emp = profile.get('employability_index_100', int(profile.get('employability_index', 8) * 10))
    
    # Filter scholarships by the best country to ensure correct recommendation
    best_country_scholarships = [s for s in funding.get('matching_scholarships', []) if s.get('country_code') == best_country_code]
    top_sch_info = max(best_country_scholarships, key=lambda s: s.get('award_amount_usd', 0), default={})
    top_scholarship = top_sch_info.get('name', 'No major scholarship matched')
    
    est_cost = next((cost.get('gross_first_year_cost_usd') for cost in funding.get('cost_analysis', []) if cost.get('country_code') == best_country_code), 12000.0)
    conf_score = min(98, max(72, int(best_c_info.get('match_score', 85) * 0.6 + overall_emp * 0.4)))
    
    import datetime
    generation_date = datetime.date.today().strftime("%B %d, %Y")
    
    # ----------------------------------------------------
    # COVER PAGE (Page 1)
    # ----------------------------------------------------
    # Background slate rectangle
    pdf.set_fill_color(15, 23, 42) # Slate 900
    pdf.rect(0, 0, 210, 297, "F")
    
    # Geometric elements
    pdf.set_fill_color(99, 102, 241) # Indigo accent
    pdf.rect(0, 0, 12, 297, "F")
    pdf.set_fill_color(168, 85, 247) # Purple accent
    pdf.rect(12, 0, 4, 297, "F")
    
    # Title
    pdf.set_y(60)
    pdf.set_font("Helvetica", "B", 28)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(20, 10, "", 0, 0) # spacer
    pdf.cell(0, 12, "AGENTBRIDGE", 0, 1, "L")
    
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(168, 85, 247) # Purple
    pdf.cell(20, 10, "", 0, 0) # spacer
    pdf.cell(0, 10, "STRATEGIC BLUEPRINT", 0, 1, "L")
    
    # Subtitle
    pdf.ln(8)
    pdf.set_font("Helvetica", "", 12)
    pdf.set_text_color(203, 213, 225) # Slate 300
    pdf.cell(20, 8, "", 0, 0)
    pdf.cell(0, 8, "Multi-Agent Global Career & Migration Assessment", 0, 1, "L")
    
    # Horizontal line
    pdf.ln(10)
    pdf.set_draw_color(99, 102, 241)
    pdf.set_line_width(0.8)
    pdf.line(35, pdf.get_y(), 195, pdf.get_y())
    pdf.set_line_width(0.2) # reset line width
    
    # Metadata Block
    pdf.ln(15)
    
    metadata = [
        ("Target Role:", profile.get('target_role', 'N/A')),
        ("Recommended Country:", f"{best_country} ({best_country_code})"),
        ("Employability Index:", f"{overall_emp}/100"),
        ("System Confidence:", f"{conf_score}%"),
        ("Generation Date:", generation_date),
        ("Version:", "1.0.0 (Production Release)")
    ]
    
    for label, val in metadata:
        pdf.cell(20, 8, "", 0, 0)
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(148, 163, 184) # Slate 400
        pdf.cell(50, 8, label, 0, 0, "L")
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(248, 250, 252) # Slate 50
        pdf.cell(0, 8, val, 0, 1, "L")
        pdf.ln(1)
        
    # Bottom Branding
    pdf.set_y(230)
    pdf.set_font("Helvetica", "I", 9.5)
    pdf.set_text_color(148, 163, 184)
    pdf.cell(20, 6, "", 0, 0)
    pdf.multi_cell(160, 5, "This strategic document is compiled using real-time relational database grounding "
                          "and multi-agent consensus validation. Verify all migration timelines and cost estimates "
                          "with official consulate portals prior to execution.\n\n"
                          "Powered by AgentBridge Collaborative Decision Network & PII Guard Redaction.")
                          
    # Transition to Page 2
    pdf.add_page()
    pdf.set_y(22)
    
    # ----------------------------------------------------
    # SECTION 1: EXECUTIVE SUMMARY
    # ----------------------------------------------------
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(99, 102, 241) # Indigo Accent
    pdf.cell(0, 8, "1. Executive Summary", 0, 1, "L")
    pdf.set_draw_color(99, 102, 241)
    pdf.line(15, pdf.get_y(), 195, pdf.get_y())
    pdf.ln(3)
    
    # Draw key metrics box
    pdf.set_fill_color(248, 250, 252) # Slate 50
    pdf.set_draw_color(226, 232, 240) # Slate 200
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(51, 65, 85) # Slate 700
    
    # Render Executive Summary Table
    pdf.cell(50, 7, "  Best Recommended Country:", "LT", 0, "L", fill=True)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(130, 7, f" {best_country} ({best_country_code})", "TR", 1, "L", fill=True)
    
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(51, 65, 85)
    pdf.cell(50, 7, "  Overall Employability Index:", "L", 0, "L", fill=True)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(130, 7, f" {overall_emp}/100", "R", 1, "L", fill=True)
    
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(51, 65, 85)
    pdf.cell(50, 7, "  Top Funding Opportunity:", "L", 0, "L", fill=True)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(130, 7, f" {top_scholarship}", "R", 1, "L", fill=True)
    
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(51, 65, 85)
    pdf.cell(50, 7, "  Gross First-Year Cost:", "L", 0, "L", fill=True)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(15, 23, 42)
    val_str = f" {symbol}{est_cost * rate:,.2f} (Before Scholarship)" if currency == "USD" else f" {symbol}{int(est_cost * rate):,} (Before Scholarship)"
    pdf.cell(130, 7, val_str, "R", 1, "L", fill=True)
    
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(51, 65, 85)
    pdf.cell(50, 7, "  System Confidence Score:", "LB", 0, "L", fill=True)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(130, 7, f" {conf_score}% (High Alignment)", "RB", 1, "L", fill=True)
    
    pdf.ln(4)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(51, 65, 85)
    pdf.cell(0, 5, "Candidate Summary Profile:", 0, 1, "L")
    pdf.set_font("Helvetica", "", 9.5)
    pdf.set_text_color(71, 85, 105)
    pdf.multi_cell(0, 5, profile.get('summary', ''))
    
    pdf.ln(6)
    
    # ----------------------------------------------------
    # SECTION 2: EMPLOYABILITY ANALYSIS
    # ----------------------------------------------------
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(99, 102, 241)
    pdf.cell(0, 8, "2. Detailed Employability Analysis", 0, 1, "L")
    pdf.set_draw_color(99, 102, 241)
    pdf.line(15, pdf.get_y(), 195, pdf.get_y())
    pdf.ln(3)
    
    pdf.set_font("Helvetica", "", 9.5)
    pdf.set_text_color(71, 85, 105)
    pdf.cell(50, 5, "Target Global Role:", 0, 0, "L")
    pdf.set_font("Helvetica", "B", 9.5)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(0, 5, profile.get('target_role', ''), 0, 1, "L")
    pdf.ln(2)
    
    # Strengths and Gaps columns
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(16, 185, 129) # Emerald
    pdf.cell(90, 5, "Core Academic & Work Strengths:", 0, 0, "L")
    pdf.set_text_color(239, 68, 68) # Red
    pdf.cell(90, 5, "Identified Critical Skill Gaps:", 0, 1, "L")
    
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(71, 85, 105)
    
    strengths = profile.get('strengths', [])
    gaps = profile.get('skill_gaps', [])
    max_len = max(len(strengths), len(gaps), 3)
    
    for i in range(max_len):
        str_text = f"- {strengths[i]}" if i < len(strengths) else ""
        gap_text = f"- {gaps[i]}" if i < len(gaps) else ""
        
        # Calculate Y positions to avoid overlaps
        start_y = pdf.get_y()
        pdf.set_x(15)
        pdf.multi_cell(85, 4.5, str_text, 0, "L")
        end_y1 = pdf.get_y()
        
        pdf.set_y(start_y)
        pdf.set_x(105)
        pdf.multi_cell(85, 4.5, gap_text, 0, "L")
        end_y2 = pdf.get_y()
        
        pdf.set_y(max(end_y1, end_y2))
        
    pdf.ln(4)
    
    # Certifications and Projects columns
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(99, 102, 241)
    pdf.cell(90, 5, "Recommended Certifications:", 0, 0, "L")
    pdf.cell(90, 5, "Recommended Projects:", 0, 1, "L")
    
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(71, 85, 105)
    
    certs = profile.get('recommended_certifications', [])
    projs = profile.get('recommended_projects', [])
    max_len2 = max(len(certs), len(projs), 3)
    
    for i in range(max_len2):
        cert_text = f"- {certs[i]}" if i < len(certs) else ""
        proj_text = f"- {projs[i]}" if i < len(projs) else ""
        
        start_y = pdf.get_y()
        pdf.set_x(15)
        pdf.multi_cell(85, 4.5, cert_text, 0, "L")
        end_y1 = pdf.get_y()
        
        pdf.set_y(start_y)
        pdf.set_x(105)
        pdf.multi_cell(85, 4.5, proj_text, 0, "L")
        end_y2 = pdf.get_y()
        
        pdf.set_y(max(end_y1, end_y2))
        
    pdf.add_page()
    
    # ----------------------------------------------------
    # SECTION 3: COUNTRY COMPARISON DASHBOARD
    # ----------------------------------------------------
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(99, 102, 241)
    pdf.cell(0, 8, "3. Country Comparison Dashboard", 0, 1, "L")
    pdf.set_draw_color(99, 102, 241)
    pdf.line(15, pdf.get_y(), 195, pdf.get_y())
    pdf.ln(4)
    
    # Table headers: Country, Match, Cost (1-Yr), Visa, Language, Post-study Work, Risk
    headers = ["Country", "Match", "Annual Cost", "Visa Complexity", "Language", "Post-Study Work", "Risk Level"]
    widths = [25, 18, 26, 32, 26, 33, 20] # Total = 180
    
    pdf.set_font("Helvetica", "B", 8.5)
    pdf.set_fill_color(99, 102, 241)
    pdf.set_text_color(255, 255, 255)
    for col_width, header in zip(widths, headers):
        pdf.cell(col_width, 8, header, border=1, align="C", fill=True)
    pdf.ln()
    
    pdf.set_font("Helvetica", "", 8.5)
    pdf.set_text_color(51, 65, 85)
    pdf.set_fill_color(248, 250, 252)
    
    # Draw rows for matched countries
    matched_list = explorer.get('matched_countries', [])
    for idx, c in enumerate(matched_list):
        code = c.get('country_code')
        # Find total first year cost from funding data
        cost_info = next((cost for cost in funding.get('cost_analysis', []) if cost.get('country_code') == code), {})
        total_cost = f"{symbol}{cost_info.get('total_1yr_usd', 0.0) * rate:,.0f}" if cost_info else "N/A"
        psw_months = f"{c.get('post_study_work_months', 0)} mos"
        
        fill = (idx % 2 == 1)
        pdf.cell(widths[0], 8, f" {c.get('country_name')}", 1, 0, "L", fill=fill)
        pdf.set_font("Helvetica", "B", 8.5)
        pdf.cell(widths[1], 8, f" {c.get('match_score')}%", 1, 0, "C", fill=fill)
        pdf.set_font("Helvetica", "", 8.5)
        pdf.cell(widths[2], 8, f" {total_cost}", 1, 0, "C", fill=fill)
        pdf.cell(widths[3], 8, f" {c.get('visa_complexity', 'Medium')}", 1, 0, "C", fill=fill)
        pdf.cell(widths[4], 8, f" {c.get('language_barrier', 'Low')}", 1, 0, "C", fill=fill)
        pdf.cell(widths[5], 8, f" {psw_months}", 1, 0, "C", fill=fill)
        
        # Color coding risk levels
        r_level = c.get('risk_level', 'Low')
        pdf.set_font("Helvetica", "B", 8.5)
        if r_level == "High":
            pdf.set_text_color(239, 68, 68) # Red
        elif r_level == "Medium":
            pdf.set_text_color(245, 158, 11) # Amber
        else:
            pdf.set_text_color(16, 185, 129) # Emerald
        pdf.cell(widths[6], 8, f" {r_level}", 1, 1, "C", fill=fill)
        pdf.set_text_color(51, 65, 85)
        pdf.set_font("Helvetica", "", 8.5)
        
    pdf.ln(5)
    
    # ----------------------------------------------------
    # SECTION 4: FINANCIAL ANALYSIS
    # ----------------------------------------------------
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(99, 102, 241)
    pdf.cell(0, 8, "4. Financial Analysis & Cost Estimates", 0, 1, "L")
    pdf.set_draw_color(99, 102, 241)
    pdf.line(15, pdf.get_y(), 195, pdf.get_y())
    pdf.ln(4)
    
    # Financial table
    fin_headers = ["Country", "Annual Tuition", "Annual Living", "Visa/App Fees", "Health Ins.", "Setup Costs", "Gross 1-Yr Cost", "ROI Score"]
    fin_widths = [20, 24, 24, 23, 23, 22, 28, 16] # Total = 180
    
    pdf.set_font("Helvetica", "B", 8.5)
    pdf.set_fill_color(99, 102, 241)
    pdf.set_text_color(255, 255, 255)
    for col_width, header in zip(fin_widths, fin_headers):
        pdf.cell(col_width, 8, header, border=1, align="C", fill=True)
    pdf.ln()
    
    pdf.set_font("Helvetica", "", 8.5)
    pdf.set_text_color(51, 65, 85)
    
    for idx, cost in enumerate(funding.get('cost_analysis', [])):
        code = cost.get('country_code')
        c_info = next((c for c in matched_list if c.get('country_code') == code), {})
        country_name = c_info.get('country_name', code)
        
        fill = (idx % 2 == 1)
        pdf.cell(fin_widths[0], 8, f" {country_name[:7]}", 1, 0, "L", fill=fill)
        pdf.cell(fin_widths[1], 8, f" {symbol}{cost.get('annual_tuition_usd', 0.0) * rate:,.0f}", 1, 0, "C", fill=fill)
        pdf.cell(fin_widths[2], 8, f" {symbol}{cost.get('annual_living_usd', 0.0) * rate:,.0f}", 1, 0, "C", fill=fill)
        pdf.cell(fin_widths[3], 8, f" {symbol}{cost.get('visa_app_fee_usd', 0.0) * rate:,.0f}", 1, 0, "C", fill=fill)
        pdf.cell(fin_widths[4], 8, f" {symbol}{cost.get('health_insurance_usd', 0.0) * rate:,.0f}", 1, 0, "C", fill=fill)
        pdf.cell(fin_widths[5], 8, f" {symbol}{cost.get('first_year_setup_usd', 0.0) * rate:,.0f}", 1, 0, "C", fill=fill)
        pdf.set_font("Helvetica", "B", 8.5)
        pdf.cell(fin_widths[6], 8, f" {symbol}{cost.get('gross_first_year_cost_usd', 0.0) * rate:,.0f}", 1, 0, "C", fill=fill)
        pdf.set_font("Helvetica", "", 8.5)
        pdf.cell(fin_widths[7], 8, f" {cost.get('financial_roi_score', 0)}/10", 1, 1, "C", fill=fill)
        
    pdf.ln(5)

    # ----------------------------------------------------
    # SECTION 4.5: BUDGET OPTIMIZED PATH
    # ----------------------------------------------------
    budget_path = calculate_budget_path(explorer, funding)
    if budget_path:
        pdf.set_font("Helvetica", "B", 13)
        pdf.set_text_color(99, 102, 241)
        pdf.cell(0, 8, "4.5 Budget Optimized Path", 0, 1, "L")
        pdf.set_draw_color(99, 102, 241)
        pdf.line(15, pdf.get_y(), 195, pdf.get_y())
        pdf.ln(3)
        
        pdf.set_fill_color(248, 250, 252) # Slate 50
        pdf.set_draw_color(226, 232, 240)
        pdf.set_font("Helvetica", "", 9.5)
        pdf.set_text_color(51, 65, 85)
        
        pdf.cell(60, 7, "  Recommended Country:", "LT", 0, "L", fill=True)
        pdf.set_font("Helvetica", "B", 9.5)
        pdf.set_text_color(15, 23, 42)
        pdf.cell(120, 7, f" {budget_path['country_name']}", "TR", 1, "L", fill=True)
        
        pdf.set_font("Helvetica", "", 9.5)
        pdf.set_text_color(51, 65, 85)
        pdf.cell(60, 7, "  University Type:", "L", 0, "L", fill=True)
        pdf.set_font("Helvetica", "B", 9.5)
        pdf.set_text_color(15, 23, 42)
        pdf.cell(120, 7, f" {budget_path['univ_type']}", "R", 1, "L", fill=True)
        
        pdf.set_font("Helvetica", "", 9.5)
        pdf.set_text_color(51, 65, 85)
        pdf.cell(60, 7, "  Estimated Scholarship Value:", "L", 0, "L", fill=True)
        pdf.set_font("Helvetica", "B", 9.5)
        pdf.set_text_color(15, 23, 42)
        pdf.cell(120, 7, f" {budget_path['scholarship_name']} ({symbol}{budget_path['scholarship_amt'] * rate:,.0f})", "R", 1, "L", fill=True)

        pdf.set_font("Helvetica", "", 9.5)
        pdf.set_text_color(51, 65, 85)
        pdf.cell(60, 7, "  Estimated Part-Time Income:", "L", 0, "L", fill=True)
        pdf.set_font("Helvetica", "B", 9.5)
        pdf.set_text_color(15, 23, 42)
        pdf.cell(120, 7, f" {symbol}{budget_path['part_time_earnings'] * rate:,.0f}", "R", 1, "L", fill=True)

        pdf.set_font("Helvetica", "", 9.5)
        pdf.set_text_color(51, 65, 85)
        pdf.cell(60, 7, "  Expected Salary / ROI:", "L", 0, "L", fill=True)
        pdf.set_font("Helvetica", "B", 9.5)
        pdf.set_text_color(15, 23, 42)
        pdf.cell(120, 7, f" {symbol}{budget_path['expected_salary'] * rate:,.0f}/yr (ROI: {budget_path['roi']}/10)", "R", 1, "L", fill=True)

        pdf.set_font("Helvetica", "", 9.5)
        pdf.set_text_color(51, 65, 85)
        pdf.cell(60, 7, "  Gross First-Year Cost:", "L", 0, "L", fill=True)
        pdf.set_font("Helvetica", "B", 9.5)
        pdf.set_text_color(15, 23, 42)
        pdf.cell(120, 7, f" {symbol}{budget_path['original_cost'] * rate:,.0f}", "R", 1, "L", fill=True)

        pdf.set_font("Helvetica", "", 9.5)
        pdf.set_text_color(51, 65, 85)
        pdf.cell(60, 7, "  Est. Net Out-of-Pocket Cost:", "L", 0, "L", fill=True)
        pdf.set_font("Helvetica", "B", 9.5)
        pdf.set_text_color(16, 185, 129) # Success Green
        pdf.cell(120, 7, f" {symbol}{budget_path['out_of_pocket'] * rate:,.0f} (Remaining)", "R", 1, "L", fill=True)

        pdf.set_font("Helvetica", "", 9.5)
        pdf.set_text_color(51, 65, 85)
        pdf.cell(60, 7, "  Affordability Score:", "LB", 0, "L", fill=True)
        pdf.set_font("Helvetica", "B", 9.5)
        pdf.set_text_color(15, 23, 42)
        pdf.cell(120, 7, f" {budget_path['affordability_score']}/10", "RB", 1, "L", fill=True)
        
        pdf.ln(3)
        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(100, 116, 139)
        pdf.multi_cell(0, 4, f"Path Analysis: {budget_path['explanation']}")
        pdf.ln(5)
    
    # ----------------------------------------------------
    # SECTION 5: SCHOLARSHIP CENTER
    # ----------------------------------------------------
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(99, 102, 241)
    pdf.cell(0, 8, "5. Scholarship Center", 0, 1, "L")
    pdf.set_draw_color(99, 102, 241)
    pdf.line(15, pdf.get_y(), 195, pdf.get_y())
    pdf.ln(3)
    
    scholarships = funding.get('matching_scholarships', [])
    if not scholarships:
        pdf.set_font("Helvetica", "I", 9.5)
        pdf.set_text_color(100, 116, 139)
        pdf.cell(0, 6, "No direct matching merit scholarships found. University fee waivers are recommended.", 0, 1, "L")
    else:
        for s in scholarships[:4]: # Limit to top 4 to save space
            pdf.set_font("Helvetica", "B", 9.5)
            pdf.set_text_color(15, 23, 42)
            pdf.cell(100, 5, s.get('name'), 0, 0, "L")
            pdf.set_font("Helvetica", "B", 9.5)
            pdf.set_text_color(16, 185, 129)
            pdf.cell(0, 5, f"Value: {symbol}{s.get('award_amount_usd', 0.0) * rate:,.0f}", 0, 1, "R")
            
            pdf.set_font("Helvetica", "I", 8.5)
            pdf.set_text_color(71, 85, 105)
            pdf.cell(100, 4.5, f"Sponsor: {s.get('sponsor')}", 0, 0, "L")
            pdf.cell(0, 4.5, f"Deadline: {s.get('deadline')}", 0, 1, "R")
            
            pdf.set_font("Helvetica", "", 8.5)
            pdf.set_text_color(100, 116, 139)
            pdf.multi_cell(0, 4.2, f"Eligibility: {s.get('eligibility_summary')}")
            pdf.ln(2.5)
            
    pdf.add_page()
    
    # ----------------------------------------------------
    # SECTION 6: SCENARIO SIMULATOR
    # ----------------------------------------------------
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(99, 102, 241)
    pdf.cell(0, 8, "6. Multi-Country Scenario Simulator", 0, 1, "L")
    pdf.set_draw_color(99, 102, 241)
    pdf.line(15, pdf.get_y(), 195, pdf.get_y())
    pdf.ln(4)
    
    if simulation and simulation.get('scenarios'):
        sim_headers = ["Scenario", "Index", "Migration Cost", "Start Salary", "Time to Job", "Visa Complexity", "Risk Profile"]
        sim_widths = [26, 18, 28, 28, 28, 30, 22] # Total = 180
        
        pdf.set_font("Helvetica", "B", 8.5)
        pdf.set_fill_color(99, 102, 241)
        pdf.set_text_color(255, 255, 255)
        for col_width, header in zip(sim_widths, sim_headers):
            pdf.cell(col_width, 8, header, border=1, align="C", fill=True)
        pdf.ln()
        
        pdf.set_font("Helvetica", "", 8.5)
        pdf.set_text_color(51, 65, 85)
        
        for idx, s in enumerate(simulation.get('scenarios', [])):
            fill = (idx % 2 == 1)
            pdf.cell(sim_widths[0], 8, f" {s.get('country_name')}", 1, 0, "L", fill=fill)
            pdf.cell(sim_widths[1], 8, f" {s.get('employability_score')}/10", 1, 0, "C", fill=fill)
            pdf.cell(sim_widths[2], 8, f" {symbol}{s.get('migration_cost_1yr_usd', 0.0) * rate:,.0f}", 1, 0, "C", fill=fill)
            pdf.cell(sim_widths[3], 8, f" {symbol}{s.get('expected_salary_usd', 0.0) * rate:,.0f}", 1, 0, "C", fill=fill)
            pdf.cell(sim_widths[4], 8, f" {s.get('time_to_employment_months')} Months", 1, 0, "C", fill=fill)
            pdf.cell(sim_widths[5], 8, f" {s.get('visa_complexity')}", 1, 0, "C", fill=fill)
            pdf.cell(sim_widths[6], 8, f" {s.get('risk_level')}", 1, 1, "C", fill=fill)
            
            # Print brief summary below in a light gray text if space permits
            # To keep layout neat, we skip printing full prose here or print it very shortly
    else:
        pdf.set_font("Helvetica", "I", 9.5)
        pdf.set_text_color(100, 116, 139)
        pdf.cell(0, 6, "Scenario simulator data not run or not loaded.", 0, 1, "L")
        
    pdf.ln(5)
    
    # ----------------------------------------------------
    # SECTION 7: STRATEGIC ROADMAP
    # ----------------------------------------------------
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(99, 102, 241)
    pdf.cell(0, 8, "7. Recommended Strategic Roadmap Plan", 0, 1, "L")
    pdf.set_draw_color(99, 102, 241)
    pdf.line(15, pdf.get_y(), 195, pdf.get_y())
    pdf.ln(4)
    
    gaps_str = ", ".join(profile.get('skill_gaps', [])[:3])
    projs_str = ", ".join(profile.get('recommended_projects', [])[:1])
    
    pdf.set_fill_color(248, 250, 252)
    pdf.set_draw_color(226, 232, 240)
    
    # Block 1
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(168, 85, 247) # Purple
    pdf.cell(0, 5, "6-Month Milestone: Profile & Skill Enhancement", 0, 1, "L")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(71, 85, 105)
    pdf.multi_cell(0, 4.5, f"- Bridge core gaps by learning: {gaps_str}.\n"
                          f"- Begin building key portfolio projects, particularly: {projs_str}.\n"
                          f"- Research specific courses and admission criteria in {best_country}.")
    pdf.ln(3)
    
    # Block 2
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(168, 85, 247)
    pdf.cell(0, 5, "1-Year Milestone: Applications & Funding Sourcing", 0, 1, "L")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(71, 85, 105)
    
    scholarship_text = f"target scholarships like: {top_scholarship}" if top_sch_info.get('name') else "target institutional fee waivers"
    pdf.multi_cell(0, 4.5, f"- Finalize admissions paperwork and sit for language/GRE standard assessments.\n"
                          f"- Apply to selected universities and {scholarship_text}.\n"
                          f"- Prepare financial proofs and blocked account funding certificates.")
    pdf.ln(3)
    
    # Block 3
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(168, 85, 247)
    pdf.cell(0, 5, "2-Year Milestone: Visa, Transition & Career Placement", 0, 1, "L")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(71, 85, 105)
    pdf.multi_cell(0, 4.5, f"- Apply for post-grad visa routes (e.g. {best_c_info.get('visa_route', 'Student Visa')}).\n"
                          f"- Transition to {best_country} and begin academic program.\n"
                          f"- Leverage local career networking & post-study permits ({best_c_info.get('post_study_work_months', 18)} months) to secure role as {profile.get('target_role')}.")
    
    # ----------------------------------------------------
    # SECTION 8: LEGAL DISCLAIMERS
    # ----------------------------------------------------
    pdf.ln(6)
    pdf.set_draw_color(226, 232, 240)
    pdf.line(15, pdf.get_y(), 195, pdf.get_y())
    pdf.ln(3)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(148, 163, 184)
    pdf.multi_cell(0, 4, "Disclaimer: Legal migration policies, visa regulations, and cost estimations change dynamically. "
                          "Always verify figures with official consulate websites. This report is generated by a multi-agent AI "
                          "decision network as a guidance blueprint and does not guarantee visa approvals or employment offers.")
    
    # Return raw PDF bytes
    return bytes(pdf.output())
